version: '2'

services:
  storage:
    image: busybox
    volumes:
      - ./:/srv

  nginx:
      image: nginx
      volumes_from:
        - storage
      volumes:
        - ./nginx/config/nginx-web.conf:/etc/nginx/conf.d/default.conf
      working_dir: /srv/www
      ports:
        - 80:80
      depends_on:
        - php

  php:
      build: php/docker
      volumes_from:
        - storage
      volumes:
        - ./php/config/php.ini:/usr/local/etc/php/php.ini
      working_dir: /srv/www
      depends_on:
        - mysql
        - memcache

  batch:
      build: php/docker
      volumes_from:
        - storage
      volumes:
        - ./php/config/php.ini:/usr/local/etc/php/php.ini
      working_dir: /srv/www
      depends_on:
        - mysql
        - memcache
      entrypoint: ["php", "/srv/batch/batch.php"]

  mysql:
      image: mysql:latest
      volumes:
        - ./mysql/data/:/var/lib/mysql
      environment:
        - MYSQL_DATABASE=uw
        - MYSQL_ROOT_PASSWORD=root

  memcache:
    image: memcached

  redis:
    image: redis:3.0.7